<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_berkas extends CI_Model
{

    public $table = 'tb_berkas';
    public $id = 'id_berkas';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_berkas,no_rek,nama_debitur,plafond,nama_mantri,lemari,rak,no_berkas');
        $this->datatables->from('tb_berkas');
        //add this line for join
        //$this->datatables->join('table2', 'tb_berkas.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('c_berkas/read/$1'),'Read')." | ".anchor(site_url('c_berkas/update/$1'),'Update')." | ".anchor(site_url('c_berkas/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Apa Kamu Yakin?\')"'), 'id_berkas');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_berkas', $q);
        $this->db->or_like('no_rek', $q);
        $this->db->or_like('nama_debitur', $q);
        $this->db->or_like('plafond', $q);
        $this->db->or_like('nama_mantri', $q);
        $this->db->or_like('lemari', $q);
        $this->db->or_like('rak', $q);
        $this->db->or_like('no_berkas', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_berkas', $q);
        $this->db->or_like('no_rek', $q);
        $this->db->or_like('nama_debitur', $q);
        $this->db->or_like('plafond', $q);
        $this->db->or_like('nama_mantri', $q);
        $this->db->or_like('lemari', $q);
        $this->db->or_like('rak', $q);
        $this->db->or_like('no_berkas', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file M_berkas.php */
/* Location: ./application/models/M_berkas.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-05-17 07:42:22 */
/* http://harviacode.com */