<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_klaim extends CI_Model
{

    public $table = 'tb_jamkrindo';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,nama,alamat,no_ktp,no_rek,no_sph,no_sertif,tgl_sertif,plafon,nilai_penjaminan,payoff,pokok_kredit,tunggakan_bunga,nama_kaunit,nama_mantri,nama_cs,tgl');
        $this->datatables->from('tb_jamkrindo');
        //add this line for join
        //$this->datatables->join('table2', 'tb_jamkrindo.field = table2.field');
        $this->datatables->add_column('action',anchor(site_url('c_jamkrindo/print/$1'),'print'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('no_ktp', $q);
	$this->db->or_like('no_rek', $q);
	$this->db->or_like('no_sph', $q);
	$this->db->or_like('no_sertif', $q);
	$this->db->or_like('tgl_sertif', $q);
	$this->db->or_like('plafon', $q);
	$this->db->or_like('nilai_penjaminan', $q);
	$this->db->or_like('payoff', $q);
	$this->db->or_like('pokok_kredit', $q);
	$this->db->or_like('tunggakan_bunga', $q);
	$this->db->or_like('nama_kaunit', $q);
	$this->db->or_like('nama_mantri', $q);
	$this->db->or_like('nama_cs', $q);
	$this->db->or_like('tgl', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('no_ktp', $q);
	$this->db->or_like('no_rek', $q);
	$this->db->or_like('no_sph', $q);
	$this->db->or_like('no_sertif', $q);
	$this->db->or_like('tgl_sertif', $q);
	$this->db->or_like('plafon', $q);
	$this->db->or_like('nilai_penjaminan', $q);
	$this->db->or_like('payoff', $q);
	$this->db->or_like('pokok_kredit', $q);
	$this->db->or_like('tunggakan_bunga', $q);
	$this->db->or_like('nama_kaunit', $q);
	$this->db->or_like('nama_mantri', $q);
	$this->db->or_like('nama_cs', $q);
	$this->db->or_like('tgl', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file M_jamkrindo.php */
/* Location: ./application/models/M_jamkrindo.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-05-20 04:46:22 */
/* http://harviacode.com */